package org.pregen.hsqldb;

// Generated Mar 30, 2012 12:35:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event implements java.io.Serializable {

	private long id;
	private Date date;
	private String desc;

	public Event() {
	}

	public Event(long id) {
		this.id = id;
	}

	public Event(long id, Date date, String desc) {
		this.id = id;
		this.date = date;
		this.desc = desc;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

}
