package org.pregen.hsqldb;

// Generated Jul 16, 2012 4:51:41 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Passwordattributes generated by hbm2java
 */
public class Passwordattributes implements java.io.Serializable {

	private String id;
	private long version;
	private Set passwordresourceauditlogs = new HashSet(0);

	public Passwordattributes() {
	}

	public Passwordattributes(String id) {
		this.id = id;
	}

	public Passwordattributes(String id, Set passwordresourceauditlogs) {
		this.id = id;
		this.passwordresourceauditlogs = passwordresourceauditlogs;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	public Set getPasswordresourceauditlogs() {
		return this.passwordresourceauditlogs;
	}

	public void setPasswordresourceauditlogs(Set passwordresourceauditlogs) {
		this.passwordresourceauditlogs = passwordresourceauditlogs;
	}

}
