package org.mapping;

// Generated Mar 7, 2012 1:42:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Passwordattributes generated by hbm2java
 */
public class Passwordattributes implements java.io.Serializable {

	private String id;
	private Long version;
	private Set passwordresourceauditlogs = new HashSet(0);

	public Passwordattributes() {
	}

	public Passwordattributes(String id) {
		this.id = id;
	}

	public Passwordattributes(String id, Set passwordresourceauditlogs) {
		this.id = id;
		this.passwordresourceauditlogs = passwordresourceauditlogs;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public Set getPasswordresourceauditlogs() {
		return this.passwordresourceauditlogs;
	}

	public void setPasswordresourceauditlogs(Set passwordresourceauditlogs) {
		this.passwordresourceauditlogs = passwordresourceauditlogs;
	}

}
