package org.diagram;

// Generated Jul 16, 2012 4:06:14 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private byte categoryId;
	private String name;
	private Date lastUpdate;
	private Set filmCategories = new HashSet(0);

	public Category() {
	}

	public Category(byte categoryId, String name, Date lastUpdate) {
		this.categoryId = categoryId;
		this.name = name;
		this.lastUpdate = lastUpdate;
	}

	public Category(byte categoryId, String name, Date lastUpdate,
			Set filmCategories) {
		this.categoryId = categoryId;
		this.name = name;
		this.lastUpdate = lastUpdate;
		this.filmCategories = filmCategories;
	}

	public byte getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(byte categoryId) {
		this.categoryId = categoryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getFilmCategories() {
		return this.filmCategories;
	}

	public void setFilmCategories(Set filmCategories) {
		this.filmCategories = filmCategories;
	}

}
