package org.diagram;

// Generated Mar 19, 2012 8:41:08 PM by Hibernate Tools 3.4.0.CR1

/**
 * Orderdetails generated by hbm2java
 */
public class Orderdetails implements java.io.Serializable {

	private Integer orderdetailnumber;
	private Orders orders;
	private Products products;
	private short orderlinenumber;
	private double priceeach;
	private int quantityordered;

	public Orderdetails() {
	}

	public Orderdetails(Orders orders, Products products,
			short orderlinenumber, double priceeach, int quantityordered) {
		this.orders = orders;
		this.products = products;
		this.orderlinenumber = orderlinenumber;
		this.priceeach = priceeach;
		this.quantityordered = quantityordered;
	}

	public Integer getOrderdetailnumber() {
		return this.orderdetailnumber;
	}

	public void setOrderdetailnumber(Integer orderdetailnumber) {
		this.orderdetailnumber = orderdetailnumber;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public short getOrderlinenumber() {
		return this.orderlinenumber;
	}

	public void setOrderlinenumber(short orderlinenumber) {
		this.orderlinenumber = orderlinenumber;
	}

	public double getPriceeach() {
		return this.priceeach;
	}

	public void setPriceeach(double priceeach) {
		this.priceeach = priceeach;
	}

	public int getQuantityordered() {
		return this.quantityordered;
	}

	public void setQuantityordered(int quantityordered) {
		this.quantityordered = quantityordered;
	}

}
