package org.diagram;

// Generated Mar 19, 2012 8:41:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private int ordernumber;
	private Customers customers;
	private String comments;
	private Date orderdate;
	private Date requireddate;
	private Date shippeddate;
	private String status;
	private Set orderdetailses = new HashSet(0);

	public Orders() {
	}

	public Orders(int ordernumber, Customers customers, Date orderdate,
			Date requireddate, String status) {
		this.ordernumber = ordernumber;
		this.customers = customers;
		this.orderdate = orderdate;
		this.requireddate = requireddate;
		this.status = status;
	}

	public Orders(int ordernumber, Customers customers, String comments,
			Date orderdate, Date requireddate, Date shippeddate, String status,
			Set orderdetailses) {
		this.ordernumber = ordernumber;
		this.customers = customers;
		this.comments = comments;
		this.orderdate = orderdate;
		this.requireddate = requireddate;
		this.shippeddate = shippeddate;
		this.status = status;
		this.orderdetailses = orderdetailses;
	}

	public int getOrdernumber() {
		return this.ordernumber;
	}

	public void setOrdernumber(int ordernumber) {
		this.ordernumber = ordernumber;
	}

	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getOrderdate() {
		return this.orderdate;
	}

	public void setOrderdate(Date orderdate) {
		this.orderdate = orderdate;
	}

	public Date getRequireddate() {
		return this.requireddate;
	}

	public void setRequireddate(Date requireddate) {
		this.requireddate = requireddate;
	}

	public Date getShippeddate() {
		return this.shippeddate;
	}

	public void setShippeddate(Date shippeddate) {
		this.shippeddate = shippeddate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getOrderdetailses() {
		return this.orderdetailses;
	}

	public void setOrderdetailses(Set orderdetailses) {
		this.orderdetailses = orderdetailses;
	}

}
