package org.diagram;

// Generated Mar 19, 2012 8:41:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private String productcode;
	private Productlines productlines;
	private double buyprice;
	private double msrp;
	private String productdescription;
	private String productname;
	private String productscale;
	private String productvendor;
	private short quantityinstock;
	private Set orderdetailses = new HashSet(0);

	public Products() {
	}

	public Products(String productcode, Productlines productlines,
			double buyprice, double msrp, String productdescription,
			String productname, String productscale, String productvendor,
			short quantityinstock) {
		this.productcode = productcode;
		this.productlines = productlines;
		this.buyprice = buyprice;
		this.msrp = msrp;
		this.productdescription = productdescription;
		this.productname = productname;
		this.productscale = productscale;
		this.productvendor = productvendor;
		this.quantityinstock = quantityinstock;
	}

	public Products(String productcode, Productlines productlines,
			double buyprice, double msrp, String productdescription,
			String productname, String productscale, String productvendor,
			short quantityinstock, Set orderdetailses) {
		this.productcode = productcode;
		this.productlines = productlines;
		this.buyprice = buyprice;
		this.msrp = msrp;
		this.productdescription = productdescription;
		this.productname = productname;
		this.productscale = productscale;
		this.productvendor = productvendor;
		this.quantityinstock = quantityinstock;
		this.orderdetailses = orderdetailses;
	}

	public String getProductcode() {
		return this.productcode;
	}

	public void setProductcode(String productcode) {
		this.productcode = productcode;
	}

	public Productlines getProductlines() {
		return this.productlines;
	}

	public void setProductlines(Productlines productlines) {
		this.productlines = productlines;
	}

	public double getBuyprice() {
		return this.buyprice;
	}

	public void setBuyprice(double buyprice) {
		this.buyprice = buyprice;
	}

	public double getMsrp() {
		return this.msrp;
	}

	public void setMsrp(double msrp) {
		this.msrp = msrp;
	}

	public String getProductdescription() {
		return this.productdescription;
	}

	public void setProductdescription(String productdescription) {
		this.productdescription = productdescription;
	}

	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	public String getProductscale() {
		return this.productscale;
	}

	public void setProductscale(String productscale) {
		this.productscale = productscale;
	}

	public String getProductvendor() {
		return this.productvendor;
	}

	public void setProductvendor(String productvendor) {
		this.productvendor = productvendor;
	}

	public short getQuantityinstock() {
		return this.quantityinstock;
	}

	public void setQuantityinstock(short quantityinstock) {
		this.quantityinstock = quantityinstock;
	}

	public Set getOrderdetailses() {
		return this.orderdetailses;
	}

	public void setOrderdetailses(Set orderdetailses) {
		this.orderdetailses = orderdetailses;
	}

}
