package org.mapping.edit;

// Generated Mar 7, 2012 1:42:51 PM by Hibernate Tools 3.4.0.CR1

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private long id;
	private String firstname;
	private String surname;

	public Customer() {
	}

	public Customer(long id) {
		this.id = id;
	}

	public Customer(long id, String firstname, String surname) {
		this.id = id;
		this.firstname = firstname;
		this.surname = surname;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

}
