package org.bdshadow;
// Generated Aug 3, 2017 4:32:17 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;

import org.hibernate.search.annotations.Analyze;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Store;
import org.hibernate.search.annotations.DocumentId;

/**
 * Actor generated by hbm2java
 */
@Indexed
public class Actor implements java.io.Serializable {

	@Id
	@DocumentId
	private short actorId;
	@Field(index=Index.YES, analyze=Analyze.YES, store=Store.YES)
	private String firstName;
	@Field(index=Index.YES, analyze=Analyze.YES, store=Store.YES)
	private String lastName;
	private Date lastUpdate;
	private Set filmActors = new HashSet(0);

	public Actor() {
	}

	public Actor(short actorId, String firstName, String lastName, Date lastUpdate) {
		this.actorId = actorId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.lastUpdate = lastUpdate;
	}

	public Actor(short actorId, String firstName, String lastName, Date lastUpdate, Set filmActors) {
		this.actorId = actorId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.lastUpdate = lastUpdate;
		this.filmActors = filmActors;
	}

	public short getActorId() {
		return this.actorId;
	}

	public void setActorId(short actorId) {
		this.actorId = actorId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getFilmActors() {
		return this.filmActors;
	}

	public void setFilmActors(Set filmActors) {
		this.filmActors = filmActors;
	}

}
